<a href="https://colab.research.google.com/github/gadilshina-ve/PDA_SOL/blob/main/03_%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**Номер 5 по списку**

α =28.

β=7.

γ=3.

θ=1.

μ – первая цифра номера студента по списку,

ν – последняя цифра номера по списку.

**Решение 1:**

In [5]:
A = np.matrix([[2, 31, -1],
               [7, 3, 5],
               [5, 50, -2]])
A

matrix([[ 2, 31, -1],
        [ 7,  3,  5],
        [ 5, 50, -2]])

In [6]:
B = np.matrix([[7, -3, 9],
               [28, 4, 5],
               [25, 10, -2]])
B

matrix([[ 7, -3,  9],
        [28,  4,  5],
        [25, 10, -2]])

In [7]:
C = np.matrix([[-1, 8, -1],
               [2, 1, 5],
               [5, 5, -2]])
C

matrix([[-1,  8, -1],
        [ 2,  1,  5],
        [ 5,  5, -2]])

In [8]:
A * B * C

matrix([[  234,  7839,  -667],
        [  164,  2445,  -189],
        [  440, 12740, -1158]])

**Решение 2:**