<a href="https://colab.research.google.com/github/gadilshina-ve/PDA_SOL/blob/main/03_%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import numpy as np

**Номер 5 по списку**

α =28.

β=7.

γ=3.

θ=1.

μ – первая цифра номера студента по списку,

ν – последняя цифра номера по списку.

**Решение 1:**

In [37]:
A = np.matrix([[2, 31, -1],
               [7, 3, 5],
               [5, 50, -2]])
A

matrix([[ 2, 31, -1],
        [ 7,  3,  5],
        [ 5, 50, -2]])

In [38]:
B = np.matrix([[7, -3, 9],
               [28, 4, 5],
               [25, 10, -2]])
B

matrix([[ 7, -3,  9],
        [28,  4,  5],
        [25, 10, -2]])

In [39]:
C = np.matrix([[-1, 8, -1],
               [2, 1, 5],
               [5, 5, -2]])
C

matrix([[-1,  8, -1],
        [ 2,  1,  5],
        [ 5,  5, -2]])

In [40]:
A * B * C

matrix([[  234,  7839,  -667],
        [  164,  2445,  -189],
        [  440, 12740, -1158]])

**Решение 2:**

In [41]:
G = np.matrix([[2, 31, 9, 6],
               [8, 3, 5, 12],
               [5, -2, 16, 6],
               [2, 7, 11, -6]])
G

matrix([[ 2, 31,  9,  6],
        [ 8,  3,  5, 12],
        [ 5, -2, 16,  6],
        [ 2,  7, 11, -6]])

Определитель:

In [42]:
det = np.linalg.det(B)
det

671.0000000000001

Обратная матрица:

In [43]:
Ginv = np.linalg.inv(G)
Ginv

matrix([[-0.06461907,  0.18468289, -0.13681691,  0.1679298 ],
        [ 0.02692461,  0.00638213, -0.02632629,  0.01336258],
        [ 0.01176705, -0.04906262,  0.07738333, -0.00897487],
        [ 0.03144529, -0.02094136,  0.06554979, -0.11155431]])

Вектор собственных значений матрицы G:

In [44]:
eig = np.linalg.eigvals(G)
eig

array([ 27.51131977, -17.00932433,  -6.07848676,  10.57649132])

**Решение 3:**

A * B = C, следовательно В = Ainv * C, Ainv - обратная матрица к A.

In [45]:
A = np.matrix([[2, -5, 7],
               [8, 1, 9],
               [3, -4, 12]])
A

matrix([[ 2, -5,  7],
        [ 8,  1,  9],
        [ 3, -4, 12]])

In [46]:
C = np.matrix([[-25, -17, 78],
               [11, 89, 76],
               [-5, 24, 115]])
C

matrix([[-25, -17,  78],
        [ 11,  89,  76],
        [ -5,  24, 115]])

Обратная матрица к A:

In [47]:
Ainv = np.linalg.inv(A)
Ainv

matrix([[ 0.24489796,  0.16326531, -0.26530612],
        [-0.35204082,  0.01530612,  0.19387755],
        [-0.17857143, -0.03571429,  0.21428571]])

Матрица B:

In [48]:
B = Ainv * C
B

matrix([[-3.,  4.,  1.],
        [ 8., 12., -4.],
        [ 3.,  5.,  8.]])

**Решение 4:**

Ax=b:

In [49]:
A = np.matrix([[3, 1, 1, 3],
               [1, -5, 5, 4],
               [-5, 0, -1, -7],
               [1, -6, 28, 6]])
A

matrix([[ 3,  1,  1,  3],
        [ 1, -5,  5,  4],
        [-5,  0, -1, -7],
        [ 1, -6, 28,  6]])

In [50]:
b = np.array([28, 7, -5, 3]).reshape(4,1)

In [51]:
from scipy.linalg import solve

In [52]:
x=solve(A,b)
for i in range(len(b)):
 print("x(%i)=%.7f" % (i+1,x[i]))

x(1)=48.7223529
x(2)=-17.0894118
x(3)=2.0729412
x(4)=-34.3835294
