<a href="https://colab.research.google.com/github/gadilshina-ve/PDA_SOL/blob/main/%D0%A1%D0%B0%D0%BC%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_2_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Самостоятельная работа 2. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [3]:
import numpy as np
print(np.__version__)

1.23.5


2) Создать нулевой вектор размера 10

In [4]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [5]:
arr = np.full((1,7) , 7)
print(arr)

[[7 7 7 7 7 7 7]]


4) Создать вектор заполненный четными числами от 10 до 100

In [6]:
arr = np.arange(10 , 101) # создадим массив чисел от 10 до 100, включительно
print(arr[(arr % 2 == 0)])

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [7]:
import random

In [8]:
arr = np.random.randint(0 , 15 , 10) # создадим массив случайных чисел из целых чисел от 0 до 15 размера 10
print(arr) #для наглядности
arr2 = arr[::-1] # массив задом напереде
print(arr2)

[12  8  2  3  5  9  9  5  4  8]
[ 8  4  5  9  9  5  3  2  8 12]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [9]:
arr =  np.arange(0, 9).reshape(3 , 3) # создадим массив из чисел от 0 до 9, не включительно, и матрицу размера 3 на 3
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [10]:
arr =  np.eye(4 , k=1)
print(arr)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других
ячейках матрицы должны быть семерки.

In [11]:
arr = np.full((4,4) , 7)
np.fill_diagonal(arr, np.arange(1, 5))
print(arr)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [12]:
arr = np.zeros((5,5))
arr += np.arange(5)
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [13]:
arr = np.random.randint(0, 10, (10,10)) # создадим массив случайных чисел из целых чисел от 0 до 10 размера 10*10
print('исходный массив 10*10:')
print(arr) #для наглядности

исходный массив 10*10:
[[3 9 5 2 3 7 9 7 1 6]
 [1 0 3 4 2 5 4 8 2 3]
 [4 4 3 6 0 6 4 7 3 3]
 [6 1 9 3 3 5 9 8 4 6]
 [6 8 3 1 8 6 4 8 3 2]
 [1 7 3 9 2 3 9 3 9 4]
 [9 7 5 8 5 2 4 2 2 7]
 [3 5 6 3 0 4 6 4 0 7]
 [7 3 3 4 2 6 3 8 9 3]
 [6 5 7 5 7 9 3 7 2 3]]


In [14]:
print('средние значения каждой строки матрицы:')
print(arr.mean(axis=1))

средние значения каждой строки матрицы:
[5.2 3.2 4.  5.4 4.9 5.  5.1 3.8 4.8 5.4]


In [15]:
print('результат вычитания из каждого элемента сторк матрицы средних значений строки:')
arr = arr - arr.mean(axis=1)
print(arr)

результат вычитания из каждого элемента сторк матрицы средних значений строки:
[[-2.2  5.8  1.  -3.4 -1.9  2.   3.9  3.2 -3.8  0.6]
 [-4.2 -3.2 -1.  -1.4 -2.9  0.  -1.1  4.2 -2.8 -2.4]
 [-1.2  0.8 -1.   0.6 -4.9  1.  -1.1  3.2 -1.8 -2.4]
 [ 0.8 -2.2  5.  -2.4 -1.9  0.   3.9  4.2 -0.8  0.6]
 [ 0.8  4.8 -1.  -4.4  3.1  1.  -1.1  4.2 -1.8 -3.4]
 [-4.2  3.8 -1.   3.6 -2.9 -2.   3.9 -0.8  4.2 -1.4]
 [ 3.8  3.8  1.   2.6  0.1 -3.  -1.1 -1.8 -2.8  1.6]
 [-2.2  1.8  2.  -2.4 -4.9 -1.   0.9  0.2 -4.8  1.6]
 [ 1.8 -0.2 -1.  -1.4 -2.9  1.  -2.1  4.2  4.2 -2.4]
 [ 0.8  1.8  3.  -0.4  2.1  4.  -2.1  3.2 -2.8 -2.4]]


11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [16]:
arr = np.random.randint(0, 10, (10,10)) # создадим массив случайных чисел из целых чисел от 0 до 10 размера 10*10
print('исходный массив 10*10:')
print(arr) #для наглядности

исходный массив 10*10:
[[5 5 8 1 7 7 6 4 5 6]
 [2 3 5 5 3 0 7 3 4 7]
 [6 5 1 3 8 5 6 7 5 8]
 [9 7 8 8 4 5 8 9 0 5]
 [2 9 7 4 2 9 3 6 9 4]
 [3 7 0 5 8 4 9 7 8 5]
 [6 5 1 1 3 2 0 8 9 0]
 [4 5 8 9 8 2 5 7 5 0]
 [9 3 5 9 9 9 0 8 4 3]
 [1 5 5 7 1 3 3 4 9 4]]


In [17]:
print('медиана по столбцам:')
print(np.median(arr , axis=0))  # медиана

медиана по столбцам:
[4.5 5.  5.  5.  5.5 4.5 5.5 7.  5.  4.5]


In [18]:
print('результат вычитания из каждого элемента столбца матрицы медианы по столбцам:')
arr = arr - np.median(arr, axis=0)
print(arr)


результат вычитания из каждого элемента столбца матрицы медианы по столбцам:
[[ 0.5  0.   3.  -4.   1.5  2.5  0.5 -3.   0.   1.5]
 [-2.5 -2.   0.   0.  -2.5 -4.5  1.5 -4.  -1.   2.5]
 [ 1.5  0.  -4.  -2.   2.5  0.5  0.5  0.   0.   3.5]
 [ 4.5  2.   3.   3.  -1.5  0.5  2.5  2.  -5.   0.5]
 [-2.5  4.   2.  -1.  -3.5  4.5 -2.5 -1.   4.  -0.5]
 [-1.5  2.  -5.   0.   2.5 -0.5  3.5  0.   3.   0.5]
 [ 1.5  0.  -4.  -4.  -2.5 -2.5 -5.5  1.   4.  -4.5]
 [-0.5  0.   3.   4.   2.5 -2.5 -0.5  0.   0.  -4.5]
 [ 4.5 -2.   0.   4.   3.5  4.5 -5.5  1.  -1.  -1.5]
 [-3.5  0.   0.   2.  -4.5 -1.5 -2.5 -3.   4.  -0.5]]


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.

In [19]:
arr = np.random.randint(0, 10, (5,5)) # создадим массив случайных чисел из целых чисел от 0 до 10 размера 5*5
print('исходный массив 5*5:')
print(arr) #для наглядности

исходный массив 5*5:
[[9 6 0 5 0]
 [6 3 6 0 4]
 [5 7 1 8 1]
 [8 1 6 3 6]
 [0 9 0 4 1]]


In [20]:
# Вычисляем максимумы и минимумы по строкам
max_values = np.max(arr, axis=0)
min_values = np.min(arr, axis=1)

In [21]:
arr_5_7 = np.column_stack((arr, max_values, min_values))  # Добавляем столбцы максимумов и минимумов к исходной матрице
print(arr_5_7)

[[9 6 0 5 0 9 0]
 [6 3 6 0 4 9 0]
 [5 7 1 8 1 6 1]
 [8 1 6 3 6 8 1]
 [0 9 0 4 1 6 0]]


13) **Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрицы. Найти произведение этих матриц. Найти обратную матрицу этого произведения.**

In [22]:
arr = np.arange(1 , 52) # создадим массив чисел от 1 до 51, включительно
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51]


In [23]:
arr1 = arr[arr % 2 != 0] #Вектор нечетных чисел
print(arr1)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51]


In [25]:
arr2=arr[(arr % 2 == 0)] #Вектор четных чисел
print(arr2)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


In [26]:
# Преобразуем векторы в матрицы с одним столбцом (меняем их размерности)
arr1 = arr1.reshape(-1, 1) # Матрица нечетных чисел
arr2 = arr2.reshape(-1, 1) #Матрица четных чисел
print('Транспонированая Матрица нечетных чисел:')
print(arr1)
print('Транспонированая Матрица четных чисел:')
print(arr2)

Транспонированая Матрица нечетных чисел:
[[ 1]
 [ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]
 [13]
 [15]
 [17]
 [19]
 [21]
 [23]
 [25]
 [27]
 [29]
 [31]
 [33]
 [35]
 [37]
 [39]
 [41]
 [43]
 [45]
 [47]
 [49]
 [51]]
Транспонированая Матрица четных чисел:
[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [12]
 [14]
 [16]
 [18]
 [20]
 [22]
 [24]
 [26]
 [28]
 [30]
 [32]
 [34]
 [36]
 [38]
 [40]
 [42]
 [44]
 [46]
 [48]
 [50]]


In [27]:
# Находим произведение матриц
multiplication_arr3 = np.dot(arr1, arr2.T)
print(multiplication_arr3)

[[   2    4    6    8   10   12   14   16   18   20   22   24   26   28
    30   32   34   36   38   40   42   44   46   48   50]
 [   6   12   18   24   30   36   42   48   54   60   66   72   78   84
    90   96  102  108  114  120  126  132  138  144  150]
 [  10   20   30   40   50   60   70   80   90  100  110  120  130  140
   150  160  170  180  190  200  210  220  230  240  250]
 [  14   28   42   56   70   84   98  112  126  140  154  168  182  196
   210  224  238  252  266  280  294  308  322  336  350]
 [  18   36   54   72   90  108  126  144  162  180  198  216  234  252
   270  288  306  324  342  360  378  396  414  432  450]
 [  22   44   66   88  110  132  154  176  198  220  242  264  286  308
   330  352  374  396  418  440  462  484  506  528  550]
 [  26   52   78  104  130  156  182  208  234  260  286  312  338  364
   390  416  442  468  494  520  546  572  598  624  650]
 [  30   60   90  120  150  180  210  240  270  300  330  360  390  420
   450  480  510  

 **Обратная матрица не существует, так как определитель произведения матрицы равен нулю**

In [35]:
#arr_inv = np.linalg.inv(multiplication_arr3)  # взятие обратной матрицы
#print(arr_inv)

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [38]:
arr = np.zeros((8,8) , dtype=int)
arr[1::2 , ::2] = 1    # слайсинг многомерных массивов (Четные строки, нечетные столбцы)
arr[::2 , 1::2] = 1    # слайсинг многомерных массивов (Нечетные строки, четные столбцы)
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
