<a href="https://colab.research.google.com/github/gadilshina-ve/PDA_SOL/blob/main/%D0%A1%D0%B0%D0%BC%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_2_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Самостоятельная работа 2. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [126]:
import numpy as np
print(np.__version__)

1.23.5


2) Создать нулевой вектор размера 10

In [127]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [128]:
arr = np.full((1,7) , 7)
print(arr)

[[7 7 7 7 7 7 7]]


4) Создать вектор заполненный четными числами от 10 до 100

In [129]:
arr = np.arange(10 , 101) # создадим массив чисел от 10 до 100, включительно
print(arr[(arr % 2 == 0)])

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [130]:
import random

In [203]:
arr = np.random.randint(0 , 15 , 10) # создадим массив случайных чисел из целых чисел от 0 до 15 размера 10
print(arr) #для наглядности
arr2 = arr[::-1] # массив задом напереде
print(arr2)

[10 11  4 11 10  1  8 14  6 11]
[11  6 14  8  1 10 11  4 11 10]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [132]:
arr =  np.arange(0, 9).reshape(3 , 3) # создадим массив из чисел от 0 до 9, не включительно, и матрицу размера 3 на 3
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [133]:
arr =  np.eye(4 , k=1)
print(arr)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других
ячейках матрицы должны быть семерки.

In [194]:
arr = np.full((4,4) , 7)
arr += np.diag([-6, -5, -4, -3])
print(arr)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [195]:
arr = np.zeros((5,5))
arr += np.arange(5)
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [419]:
arr = np.random.randint(0, 10, (10,10)) # создадим массив случайных чисел из целых чисел от 0 до 10 размера 10*10
print('исходный массив 10*10:')
print(arr) #для наглядности

исходный массив 10*10:
[[8 4 0 1 1 7 7 4 5 1]
 [6 8 6 4 1 6 2 1 9 5]
 [7 6 0 5 5 5 0 2 9 8]
 [5 2 6 4 4 8 8 2 3 7]
 [3 6 1 5 3 6 2 4 7 4]
 [7 3 5 1 1 0 0 7 8 5]
 [9 9 1 0 2 7 0 8 2 4]
 [9 8 3 6 5 7 3 9 8 1]
 [6 7 7 9 0 6 7 1 3 8]
 [4 7 6 8 4 1 4 1 1 8]]


In [420]:
print('средние значения каждой строки матрицы:')
print(arr.mean(axis=1))

средние значения каждой строки матрицы:
[3.8 4.8 4.7 4.9 4.1 3.7 4.2 5.9 5.4 4.4]


In [421]:
print('результат вычитания из каждого элемента сторк матрицы средних значений строки:')
arr = arr - arr.mean(axis=1)
print(arr)

результат вычитания из каждого элемента сторк матрицы средних значений строки:
[[ 4.2 -0.8 -4.7 -3.9 -3.1  3.3  2.8 -1.9 -0.4 -3.4]
 [ 2.2  3.2  1.3 -0.9 -3.1  2.3 -2.2 -4.9  3.6  0.6]
 [ 3.2  1.2 -4.7  0.1  0.9  1.3 -4.2 -3.9  3.6  3.6]
 [ 1.2 -2.8  1.3 -0.9 -0.1  4.3  3.8 -3.9 -2.4  2.6]
 [-0.8  1.2 -3.7  0.1 -1.1  2.3 -2.2 -1.9  1.6 -0.4]
 [ 3.2 -1.8  0.3 -3.9 -3.1 -3.7 -4.2  1.1  2.6  0.6]
 [ 5.2  4.2 -3.7 -4.9 -2.1  3.3 -4.2  2.1 -3.4 -0.4]
 [ 5.2  3.2 -1.7  1.1  0.9  3.3 -1.2  3.1  2.6 -3.4]
 [ 2.2  2.2  2.3  4.1 -4.1  2.3  2.8 -4.9 -2.4  3.6]
 [ 0.2  2.2  1.3  3.1 -0.1 -2.7 -0.2 -4.9 -4.4  3.6]]


11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [422]:
arr = np.random.randint(0, 10, (10,10)) # создадим массив случайных чисел из целых чисел от 0 до 10 размера 10*10
print('исходный массив 10*10:')
print(arr) #для наглядности

исходный массив 10*10:
[[3 9 7 2 2 5 7 4 3 2]
 [3 8 3 4 5 1 4 9 4 5]
 [9 3 2 1 8 0 0 7 9 1]
 [9 0 3 7 1 0 9 9 5 6]
 [1 4 5 1 1 0 2 4 2 3]
 [7 5 4 3 4 8 1 6 4 6]
 [5 5 0 4 5 7 8 7 6 1]
 [9 5 9 3 6 4 7 9 6 3]
 [7 8 6 5 8 1 9 8 0 4]
 [4 7 8 5 2 9 3 0 9 4]]


In [423]:
print('медиана по столбцам:')
print(np.median(arr , axis=0))  # медиана

медиана по столбцам:
[6.  5.  4.5 3.5 4.5 2.5 5.5 7.  4.5 3.5]


In [424]:
print('результат вычитания из каждого элемента столбца матрицы медианы по столбцам:')
arr = arr - np.median(arr, axis=0)
print(arr)


результат вычитания из каждого элемента столбца матрицы медианы по столбцам:
[[-3.   4.   2.5 -1.5 -2.5  2.5  1.5 -3.  -1.5 -1.5]
 [-3.   3.  -1.5  0.5  0.5 -1.5 -1.5  2.  -0.5  1.5]
 [ 3.  -2.  -2.5 -2.5  3.5 -2.5 -5.5  0.   4.5 -2.5]
 [ 3.  -5.  -1.5  3.5 -3.5 -2.5  3.5  2.   0.5  2.5]
 [-5.  -1.   0.5 -2.5 -3.5 -2.5 -3.5 -3.  -2.5 -0.5]
 [ 1.   0.  -0.5 -0.5 -0.5  5.5 -4.5 -1.  -0.5  2.5]
 [-1.   0.  -4.5  0.5  0.5  4.5  2.5  0.   1.5 -2.5]
 [ 3.   0.   4.5 -0.5  1.5  1.5  1.5  2.   1.5 -0.5]
 [ 1.   3.   1.5  1.5  3.5 -1.5  3.5  1.  -4.5  0.5]
 [-2.   2.   3.5  1.5 -2.5  6.5 -2.5 -7.   4.5  0.5]]


12) **Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.**

In [436]:
arr = np.random.randint(0, 10, (5,5)) # создадим массив случайных чисел из целых чисел от 0 до 10 размера 5*5
print('исходный массив 5*5:')
print(arr) #для наглядности

исходный массив 5*5:
[[9 1 4 9 5]
 [0 6 6 7 8]
 [2 1 6 2 6]
 [7 9 1 9 2]
 [0 5 0 5 2]]


13) **Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрицы. Найти произведение этих матриц. Найти обратную матрицу этого произведения.**

In [496]:
arr = np.arange(1 , 52) # создадим массив чисел от 1 до 51, включительно

In [497]:
arr2=arr[(arr % 2 == 0)]
print(arr2)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [434]:
arr = np.ones((3,3))
arr = np.zeros((8,8),dtype=int)
arr[1::2,::2] = 1    # слайсинг многомерных массивов
arr[::2,1::2] = 1    # слайсинг многомерных массивов
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
